### ISSUE TITLE
Alternative License?

### ISSUE THREAD

**Issue by sandeepmistry** [adafruit/Adafruit-Trinket-USB#10]
Just wondering if the license could be changed to something more permissive, such as MIT or BSD, instead of the current LGPL license.

I was hope to re-use some of the constants and maybe the HID descriptor in the new HID over GATT API for my [BLEPeripheral](https://github.com/sandeepmistry/arduino-BLEPeripheral) library which is under a MIT license.

Particularly:
 * KEYCODE_*, MMKEY_*,  SYSCTRLKEY_* from [TrinketHidCombo/TrinketHidCombo.h](https://github.com/adafruit/Adafruit-Trinket-USB/blob/master/TrinketHidCombo/TrinketHidCombo.h#L82)
 * usbHidReportDescriptor from [TrinketHidCombo/TrinketHidComboC.c](https://github.com/adafruit/Adafruit-Trinket-USB/blob/master/TrinketHidCombo/TrinketHidComboC.c#L81)

@microbuilder suggested I raise an issue here.

**Comment by ladyada** [comment]
hiya, in keeping with the ObDev library, we kept the overall license LGPL
however, since i'm the copyright holder, go ahead and use those structures from those 2 files with my blessing you can put them in MIT lic code :)

**Comment by sandeepmistry** [comment]
@ladyada great! Thank you :)
