### ISSUE TITLE
TrinketHidCombo.getLEDstate() not working

### ISSUE THREAD

**Issue by maujabur** [adafruit/Adafruit-Trinket-USB#8]
Hi!

When using TrinketHidCombo, the function getLEDstate() seems to be returning always 0, but for TrinketKeyboard it works fine!

test code: 

    // Adafruit Arduino 1.05 - Win 9-15-14
    // trinket 5V
    
    #include <Bounce.h>
    #include <TrinketKeyboard.h>
    //#include <TrinketHidCombo.h>
    
    #define LED_CAPS 1
    
    
    void setup() {
      pinMode(LED_CAPS,OUTPUT);
      TrinketKeyboard.begin();
      //TrinketHidCombo.begin();
    }
    
    void loop() {
      delay(5);

      TrinketKeyboard.poll();
      digitalWrite(LED_CAPS, (TrinketKeyboard.getLEDstate()&KB_LED_CAPS)?HIGH:LOW);
      //TrinketHidCombo.poll();
      //digitalWrite(LED_CAPS, (TrinketHidCombo.getLEDstate()&KB_LED_CAPS)?HIGH:LOW);
    }

**Comment by ElectricRCAircraftGuy** [comment]
Same here. getLEDstate() is broken for the TrinketHidCombo library but *not* for the TrinketKeyboard library. Additionally, there is a bug with the print function. I'll open a new issue for that bug.

**Comment by ElectricRCAircraftGuy** [comment]
Please close this issue; it is now fixed. See here: https://github.com/adafruit/Adafruit-Trinket-USB/commit/51f208bc569dd79d7357f16d548ed0c43f4927e8

I've tested it and it works now.

**Comment by maujabur** [comment]
Thanks! I can't test it right now, but I'll close it anyway, since you tested it!
